version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80 # 暴露端口
    volumes:  # 挂载
      - /mydata/nginx/html:/usr/share/nginx/html
      - /mydata/nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true #解决 nginx 的文件调用权限问题
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=hc2919
  redis:
    image: redis:latest
  mall:
    image: mall:latest
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - redis
